# Generated by Django 2.1.3 on 2018-11-06 20:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=30, verbose_name='Children name')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=30, verbose_name='Family name')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=30, verbose_name='Parent name')),
                ('parent_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familytodo.Family', verbose_name='Parent family')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30, verbose_name='Task')),
                ('task_importance', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=3, verbose_name='Importance')),
                ('task_reward', models.CharField(blank=True, max_length=30, null=True, verbose_name='Reward')),
                ('task_due', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Due days')),
                ('task_child', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='familytodo.Child', verbose_name='Task belongs to child')),
                ('task_family', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='familytodo.Family', verbose_name='Task belongs to family')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='child_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familytodo.Family', verbose_name='Family of child'),
        ),
    ]
