# Generated by Django 2.1.3 on 2018-11-06 19:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import familytodo.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_model', models.CharField(max_length=30, verbose_name='Children name')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=30, verbose_name='Family name')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Parent name')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familytodo.Family', verbose_name='Parent family')),
            ],
        ),
        migrations.CreateModel(
            name='Taks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taks_name', models.CharField(max_length=30, verbose_name='Task')),
                ('taks_importance', models.CharField(choices=[(familytodo.enums.Importance('High'), 'High'), (familytodo.enums.Importance('Medium'), 'Medium'), (familytodo.enums.Importance('Low'), 'Low')], max_length=3, verbose_name='Importance')),
                ('task_reward', models.CharField(blank=True, max_length=30, null=True, verbose_name='Reward')),
                ('taks_due', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Due days')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familytodo.Family', verbose_name='Family of child'),
        ),
    ]
