# Generated by Django 2.1.3 on 2018-11-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytodo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taks',
            new_name='Task',
        ),
    ]
