# Generated by Django 2.1.3 on 2018-11-06 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytodo', '0002_auto_20181106_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='child_model',
            new_name='child_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='name',
            new_name='parent_name',
        ),
        migrations.AddField(
            model_name='task',
            name='task_child',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='familytodo.Child', verbose_name='Task belongs to child'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_family',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='familytodo.Family', verbose_name='Task belongs to family'),
        ),
    ]
