# Generated by Django 2.1.3 on 2018-11-06 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytodo', '0003_auto_20181106_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='family',
            new_name='child_family',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='family',
            new_name='parent_family',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taks_due',
            new_name='task_due',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taks_importance',
            new_name='task_importance',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taks_name',
            new_name='task_name',
        ),
    ]
