# Generated by Django 2.0.4 on 2018-04-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Family',
        ),
    ]
