# Generated by Django 2.0.4 on 2018-05-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_kids'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='nujnost',
            field=models.CharField(default='2', max_length=1),
        ),
    ]
