# Generated by Django 2.0.4 on 2018-05-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_nujnost'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='ime_otroka',
            field=models.CharField(default='', max_length=10),
        ),
    ]
