# Generated by Django 2.1.5 on 2019-01-08 22:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=30, verbose_name='Children name')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=30, verbose_name='Family name')),
                ('family_username', models.CharField(max_length=30, null=True, unique=True, verbose_name='Family username')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('easy_password', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Easy Password')),
                ('ac_type', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=4, verbose_name='Account type')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=30, verbose_name='Parent name')),
                ('parent_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='familytodo.Family', verbose_name='Parent family')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_desc', models.CharField(max_length=30, verbose_name='Schedule')),
                ('schedule_day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tudesday'), ('WEDENSDAY', 'Wedensday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10, verbose_name='Day of this schedule')),
                ('schedule_time', models.TimeField(blank=True, null=True, verbose_name='Time in that day')),
                ('schedule_child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='familytodo.Child', verbose_name='Schedule belongs to child')),
                ('schedule_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='familytodo.Family', verbose_name='Schedule belongs to family')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30, verbose_name='Task')),
                ('task_importance', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=6, verbose_name='Importance')),
                ('task_reward', models.CharField(blank=True, max_length=30, null=True, verbose_name='Reward')),
                ('task_due', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Due days')),
                ('task_complete', models.BooleanField(default=False)),
                ('task_child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='familytodo.Child', verbose_name='Task belongs to child')),
                ('task_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='familytodo.Family', verbose_name='Task belongs to family')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='child_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familytodo.Family', verbose_name='Family of child'),
        ),
    ]
