# Generated by Django 2.1.3 on 2018-11-15 18:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='easy_password',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Easy Password'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='familytodo.Family', verbose_name='Parent family'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='familytodo.Child', verbose_name='Task belongs to child'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='familytodo.Family', verbose_name='Task belongs to family'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_importance',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=6, verbose_name='Importance'),
        ),
    ]
