# Generated by Django 2.1.3 on 2018-11-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytodo', '0002_auto_20181115_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='family_username',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Family username'),
        ),
    ]
