# Generated by Django 2.1.2 on 2018-11-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytodo', '0003_family_family_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='ac_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default=None, max_length=4, verbose_name='Account type'),
            preserve_default=False,
        ),
    ]
