# Generated by Django 2.1.2 on 2018-12-19 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytodo', '0004_family_ac_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_desc', models.CharField(max_length=30, verbose_name='Schedule')),
                ('schedule_day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tudesday'), ('WEDENSDAY', 'Wedensday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10, verbose_name='Day of this schedule')),
                ('schedule_child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='familytodo.Child', verbose_name='Schedule belongs to child')),
                ('schedule_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='familytodo.Family', verbose_name='Schedule belongs to family')),
            ],
        ),
    ]
