# Generated by Django 2.1.3 on 2018-12-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytodo', '0005_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time in that day'),
        ),
    ]
